#!/bin/bash
[[ -f ./setup ]] && source ./setup

GAMEID=${GAMEID:-"minimal"}

pushd /root > /dev/null
    exec su-exec minetest:games minetestserver --config /etc/minetest/minetest.conf --gameid ${GAMEID}
popd
